### PR TITLE
Update to React Native 0.40

### PR DESCRIPTION
**Pull request by bradbyte**
From https://github.com/ccm-innovation/react-native-twilio-ip-messaging/pull/58.

### CODE REVIEW

**Comment by benoist** [comment]
Any idea when this will be merged?

**Comment by bradbyte** [comment]
@benoist sorry -- I will revisit this and see if we can't get this merged.

**Comment by benoist** [comment]
That would be great :) Happy to help with anything if required.

**Comment by bradbyte** [comment]
@benoist released in 0.3.0.

**Comment by benoist** [comment]
Tnx I will test it tomorrow

**Pull request merged**
