### PR TITLE
Send attributed messages

### PR DESCRIPTION
**Pull request by bradbyte**
Moved over from https://github.com/ccm-innovation/react-native-twilio-ip-messaging/pull/73.

### CODE REVIEW

**Comment by bradbyte** [comment]
This fixes #7 .

**Review by svlaev — APPROVED** [review]
This  PR allows attributed messages to be sent

**Comment by svlaev** [comment]
Hello, @bradbumbalough! Please Approve this PR. Thanks!

**Comment by bradbyte** [comment]
Hey @svlaev I'm sorry I didn't make it back here yet. I've been mulling over it more and I'l like to propose a change for your consideration. Our approach to this package has been to a) wrap the existing SDK methods, or b) if that didn't make sense follow the JS SDK. So, with respect to this I think it would be best to either map the methods as the SDK handles it, or, expand the `sendMessage` to take a 2nd param of `attributes` (which follows the [JS SDK](https://media.twiliocdn.com/sdk/js/chat/releases/0.12.0/docs/Channel.html#sendMessage__anchor)). I think the 2nd one would be easier as we won't have to convert the the JSON over the bridge into a Message instance. Thoughts?

**Review by svlaev — APPROVED** [review]
Followed JS SDK approach for the method allowing us to send attributed messages.

**Comment by bradbyte** [comment]
Closing in light of #17.

**Pull request closed without merging**
