### PR TITLE
Fix compile on iOS

### PR DESCRIPTION
**Pull request by benoist**
I've removed the references to the twilio pod files and fixed the projects search paths.
I also used the new React import style

### CODE REVIEW

**Comment by benoist** [comment]
FYI I used this with React Native 0.43.3

**Comment by bradbyte** [comment]
@benoist do you want to update the Readme too to provide notes on installing w/o CocoaPods?

**Comment by benoist** [comment]
Well you still need cocoapods to install the twilio libraries in the main project. It's just that this library does not have any references to the twilio library, but expects the main project to have them included and uses the search locations to find the header files.

**Comment by bradbyte** [comment]
Oh got it. That makes it much cleaner. I think you can manually download the SDKs, but that doesn't have to be in the scope of this push.

**Review by despacito — APPROVED** [review]

**Review by despacito — APPROVED** [review]

**Review by mcatmos — APPROVED** [review]

**Review by bradbyte — APPROVED** [review]

**Review by bradbyte — APPROVED** [review]

**Pull request merged**
