### PR TITLE
Support sdks v1.0

### PR DESCRIPTION
**Pull request by svlaev**
Implements #9

### CODE REVIEW

**Comment by svlaev** [comment]
@bradbumbalough Hi! Here's the migration done. 
Feel free to tell me if you have any doubts about it

**Comment by bradbyte** [comment]
@svlaev Thanks! I will look at this today.

**Review by despacito — APPROVED** [review]

**Comment by svlaev** [comment]
@bradbumbalough It sill needs some work, so maybe we can merge it into a branch different than **master** and continue working on it there

**Comment by bradbyte** [comment]
That's a good idea... Do you want to close and reopen this? I made a branch called `1.0-rc1`.

**Pull request closed without merging**
